import abc
import pathlib
import sqlite3
from _typeshed import Incomplete
from abc import ABC, abstractmethod
from dataclasses import dataclass
from langchain_core.tools import BaseTool as BaseTool
from psycopg import Connection
from pydantic import BaseModel
from typing import Any, Generic, Literal, Protocol, Self, TypeVar, override
from typing_extensions import Iterable

class UnifiedMemorySchema(BaseModel):
    command: Literal['view', 'create', 'str_replace', 'insert', 'delete', 'rename']
    path: str | None
    view_range: list[int] | None
    file_text: str | None
    old_str: str | None
    new_str: str | None
    insert_line: int | None
    insert_text: str | None
    old_path: str | None
    new_path: str | None

class MemoryBackendError(RuntimeError):
    def __init__(self, msg: str) -> None: ...

class MemoryBackend(ABC, metaclass=abc.ABCMeta):
    @dataclass
    class FileStat:
        exists: bool
        is_dir: bool
    @abstractmethod
    def read_file(self, path: str) -> str | None: ...
    @abstractmethod
    def write_file(self, path: str, content: str): ...
    @abstractmethod
    def stat(self, path: str) -> FileStat: ...
    @abstractmethod
    def list_dir(self, path: str) -> Iterable[tuple[str, bool]]: ...
    @abstractmethod
    def rm(self, path: str) -> str: ...
    @abstractmethod
    def do_rename(self, old_path: str, new_path: str) -> str: ...
    def view(self, path: str, view_range: tuple[int, int] | None) -> str: ...
    def create(self, path: str, content: str) -> str: ...
    def delete(self, path: str) -> str: ...
    def rename(self, old_path: str, new_path: str) -> str: ...
    def insert(self, path: str, insert_line: int, insert_text: str) -> str: ...
    def str_replace(self, path: str, old_str: str, new_str: str) -> str: ...

class DBCursor(Protocol):
    def execute(self, query: str, vars: tuple[Any, ...] | dict[str, Any], /) -> Any: ...
    def fetchone(self, /) -> None | tuple[Any, ...]: ...
    def close(self) -> None: ...
    def __iter__(self) -> Self: ...
    def __next__(self) -> tuple[Any, ...]: ...
    @property
    def rowcount(self) -> int: ...

class DBConnection(Protocol):
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: Any | None) -> bool | None: ...
    def cursor(self, /) -> DBCursor: ...
CONN = TypeVar('CONN')
CURSOR = TypeVar('CURSOR', bound=DBCursor)

class SQLBackend(MemoryBackend, Generic[CONN], metaclass=abc.ABCMeta):
    conn: Incomplete
    ns: Incomplete
    def __init__(self, ns: str, conn: CONN) -> None: ...
    @property
    @abstractmethod
    def pos_placeholder(self) -> str: ...
    @abstractmethod
    def named_placeholder(self, nm: str) -> str: ...
    @abstractmethod
    def do_replace_first(self, replace_attribute: str, to_replace: str, replace_with: str, seq: int) -> tuple[str, dict[str, str]]: ...
    @override
    def do_rename(self, old_path: str, new_path: str) -> str: ...
    @override
    def list_dir(self, path: str) -> Iterable[tuple[str, bool]]: ...
    @override
    def rm(self, path: str) -> str: ...
    @override
    def read_file(self, path: str) -> str | None: ...
    @override
    def write_file(self, path: str, content: str): ...
    @override
    def stat(self, path: str) -> MemoryBackend.FileStat: ...

class PostgresMemoryBackend(SQLBackend[Connection]):
    def __init__(self, ns: str, conn: Connection) -> None: ...
    @property
    def pos_placeholder(self) -> str: ...
    @override
    def named_placeholder(self, nm: str) -> str: ...
    @override
    def do_replace_first(self, replace_attribute: str, to_replace: str, replace_with: str, seq: int) -> tuple[str, dict[str, str]]: ...
    def __del__(self) -> None: ...

class SqliteMemoryBackend(SQLBackend[sqlite3.Connection]):
    def __init__(self, ns: str, conn: sqlite3.Connection) -> None: ...
    @property
    def pos_placeholder(self) -> str: ...
    @override
    def named_placeholder(self, nm: str) -> str: ...
    @override
    def do_replace_first(self, replace_attribute: str, to_replace: str, replace_with: str, seq: int) -> tuple[str, dict[str, str]]: ...

class FileSystemMemoryBackend(MemoryBackend):
    memory_root: Incomplete
    def __init__(self, storage_folder: pathlib.Path) -> None: ...
    @override
    def stat(self, path: str) -> MemoryBackend.FileStat: ...
    @override
    def write_file(self, path: str, content: str): ...
    @override
    def read_file(self, path: str) -> str | None: ...
    @override
    def do_rename(self, old_path: str, new_path: str) -> str: ...
    @override
    def rm(self, path: str) -> str: ...
    @override
    def list_dir(self, path: str) -> Iterable[tuple[str, bool]]: ...

def memory_tool(backend: MemoryBackend) -> BaseTool: ...
