name: pyright-check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-nodeps-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-nodeps-

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install requirements
        run: |
            egrep '^(sentence-)?transformers' requirements.txt > transformer-reqs.txt
            pip install -r ./transformer-reqs.txt --no-deps
            egrep -v '^(nvidia-|torch|((sentence-)?transformers))' requirements.txt > pyright-reqs.txt
            pip install -r pyright-reqs.txt

      - name: Run pyright
        uses: jakebailey/pyright-action@v3
        with:
          python-path: ${{ env.pythonLocation }}/bin/python
